# config/deploy.production.yml
servers:
  web:
    hosts:
      - 193.203.183.47
    options:
      network: "marshall-network"

ssh:
  user: concordiauser
  port: 22
  keys_only: true

proxy:
  ssl: true
  host: thiagolamberti.com.br
  app_port: 80
  healthcheck:
    path: /health

env:
  clear:
    APP_ENV: main
    HOSTNAME: 0.0.0.0
