name: Build and Deploy - LP Thiago Lamberti

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build_and_push:
    name: Build & Push Image to GHCR
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: lp-thiago-lamberti

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build imagem
        run: |
          REPO_OWNER_LOWER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          docker build -t ghcr.io/${REPO_OWNER_LOWER}/${IMAGE_NAME}:latest .

      - name: Push imagem
        run: |
          REPO_OWNER_LOWER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          docker push ghcr.io/${REPO_OWNER_LOWER}/${IMAGE_NAME}:latest

  deploy:
    name: Pull & Run on Server
    runs-on: self-hosted
    needs: build_and_push

    env:
      IMAGE_NAME: lp-thiago-lamberti

    steps:
      - name: Login GHCR (no servidor)
        run: |
          REPO_OWNER_LOWER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${REPO_OWNER_LOWER} --password-stdin

      - name: Pull da nova imagem
        run: |
          REPO_OWNER_LOWER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          docker pull ghcr.io/${REPO_OWNER_LOWER}/${IMAGE_NAME}:latest

      - name: Parar e remover container antigo
        run: |
          docker stop ${IMAGE_NAME} || true
          docker rm ${IMAGE_NAME} || true

      - name: Subir container novo
        run: |
          REPO_OWNER_LOWER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          docker run -d \
            --name ${IMAGE_NAME} \
            --restart unless-stopped \
            -p 9988:80 \
            ghcr.io/${REPO_OWNER_LOWER}/${IMAGE_NAME}:latest

      - name: Limpeza de imagens antigas
        run: |
          docker image prune -f || true
